import random

AI_NICKNAMES = [
    "Senator SegFault", 
    "Captain BufferOverflow",
    "Lady Tokenizer",
    "Infinite Loop",
    "Mr. Null Pointer",
    "Congressman 404",
    "Chief Memory Leak",
    "Dame Denial-of-Service",
    "Governor Glitch",
    "Recursive Rep.",
    "General Cloud",
    "Admiral Firewall",
    "Chief Cache-Memory",
    "Duchess of the Router",
    "Sir Terabyte",
    "Lord Load Balancer",
    "GPU Guru",
    "Copper Cable King",
    "Senator Solid-State",
    "Baron Big Data",
    "Dr. Perceptron",
    "Madame Neural Network",
    "DeepFake Duke",
    "Predictor Prompt",
    "Brother TensorFlow",
    "Generative Governor",
    "Syntax Splicer",
    "Bias Baron",
    "Lady Latent Space",
    "Algorithm Ally",
    "Warden Weight Decay",
    "Sir Stochastic Gradient",
    "Kernel King",
    "Prophet of PyTorch",
    "Regression Rep",
    "Hacker of Hope",
    "Phishing Pirate",
    "Malware Maria",
    "Proxy Priest",
    "Colonel Cryptography",
    "Zero-Day Zealot",
    "Sudo Senator",
    "Trojan Troll",
    "Encrypted Elder",
    "Chief of Cipher",
    "Mister Ctrl+C",
    "Binary Bishop",
    "Syntax Sage",
    "Debugger Duke",
    "Python Preacher",
    "JSON Jockey",
    "API Apostle",
    "Lambda Legislator",
    "Forkbomb Frank",
    "README Rep",
    "Reboot Rex",
    "Senator Streaming",
    "Backup Baroness",
    "Patchwork Pol",
    "Protocol Prince",
    "Latency Lord",
    "Gigahertz Guardian",
    "USB Unit",
    "Zip File Zeke",
    "Pixel Patriot",
    "Missing Semicolon",
    "Deprecated Dean",
    "Hard Reset Henry",
    "Read-Only Randy",
    "Bootloader Bob",
    "Emojicon Eddie",
    "Hashtag Honcho",
    "Wiki Warrior",
    "Spreadsheet Swami",
    "Excel Lord",
    "LSTM Leader",
    "Bayesian Boss",
    "Markov Model Man",
    "Chatbot Chad",
    "Robotics Rex",
    "GPT Governor",
    "Fine-Tuning Finn",
    "Prompt Politician",
    "Vector Visionary",
    "Tensor Tsar",
    "Floppy Disk Don",
    "Dial-Up Duke",
    "Modem Mike",
    "VGA Visionary",
    "ASCII Advocate",
    "Byte Baron",
    "Octal Officer",
    "Hexadecimal Hank",
    "Mainframe Max",
    "Telepresence Tom",
    "Cloud Commander",
    "Quantum Query",
    "Neural Net Nick",  
    "Dataframe Dave",
    "Script Kiddie",
    "AI Architect",
    "Cyber Senator",
]

def assign_nickname(rng: random.Random) -> str:
    return rng.choice(AI_NICKNAMES)